name: publish GitHub release
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: ja jp
      run: sudo apt -y install language-pack-ja && sudo update-locale LANG=ja_JP.UTF8
    - name: check locale
      run: locale -a
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache
      uses: actions/cache@v1.0.0
      with:
        path: ~/.m2
        key: ${{ hashFiles('pom.xml') }}
    - name: Build with Maven
      run: LANG=ja_JP.UTF8 mvn -B verify --file pom.xml -Dmaven.javadoc.failOnError=false
    - name: publish assets
      uses: AButler/upload-release-assets@v1.0
      with:
        files: target/*.zip
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release-tag: ${{ github.ref }}
